# This workflow builds and uploads python artifacts

name: Publish Development Package
on:
  push:
    branches:
      - master

jobs:
  build-n-publish-package:
    permissions:
      actions: write
      contents: write
      id-token: write
    uses: irvingleonard/reusable-workflows/.github/workflows/python-build-publish-development-package.yml@v1
    with:
      package-name: ${{ vars.PACKAGE_NAME }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
